# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - func-app-test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Set environment variables for the workflow'
        required: true
        type: choice
        options: ['optumnonprod', 'optumprod']
      ACTION:
        description: 'Set the action to perform'
        required: true
        type: choice
        options: ['deploy', 'build']

env:
  ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT || 'optumnonprod' }}
  AZURE_FUNCTIONAPP_NAME: func-app-test # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '21' # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83B39520D07D49FDB1D61441FEF7016F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_152AFA14F7144156AF2C175EAA2A9793 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BBAD442020148D08924C4FC2A3A605F }}



      - name: Apply appSettings.json
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name "${{ env.AZURE_FUNCTIONAPP_NAME }}" \
              --resource-group "<YOUR_RESOURCE_GROUP>" \
              --settings @"${{ env.ENVIRONMENT }}/appSettings.json"
      

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'func-app-test'
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
          
